// app/r/[id]/page.tsx —— 可分享的只读核实报告 (服务端渲染, 公开)。
// 把一条 research_runs 渲染成"带证据的核实报告", 可直接发给客户/投资人。
import Link from "next/link";
import type { Metadata } from "next";
import { FiArrowRight } from "react-icons/fi";
import { getRunById } from "@/lib/db";
import {
  CandidateCard,
  CandidateComparisonView,
  CandidateProfileView,
  CoverageBackfillView,
  EvidenceCoverageView,
  EvidenceGraphView,
  SearchPlanView,
  ShortlistDeliveryReportView,
  SourceExecutionView,
  TalentMapView,
  TrustReportView,
  type Claim,
  type Candidate,
  type VerifyReport,
} from "@/components/result";
import {
  isTalentSearchResult,
  normalizeTalentSearchResult,
  type TalentSearchResult,
} from "@/lib/talent-profile.mjs";
import { normalizeLocale } from "@/lib/i18n.mjs";

type Locale = "zh" | "en";

export const runtime = "nodejs";
const REPORT_FETCH_TIMEOUT_MS = 4500;

function LogoMark({ className = "" }: { className?: string }) {
  return (
    <svg viewBox="0 0 512 512" className={className} aria-hidden="true">
      <g stroke="#111111" strokeWidth={22} fill="none" strokeLinecap="round">
        <circle cx="256" cy="256" r="130" />
        <circle cx="256" cy="256" r="70" />
        <path d="M186 256a70 70 0 1 0 70-70" />
      </g>
      <circle cx="256" cy="256" r="16" fill="#9EFF4F" />
    </svg>
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function cleanString(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function getRunByIdWithTimeout(id: string) {
  return Promise.race([
    getRunById(id),
    new Promise<null>((resolve) => setTimeout(() => resolve(null), REPORT_FETCH_TIMEOUT_MS)),
  ]);
}

const REPORT_COPY = {
  zh: {
    missingTitle: "报告不存在或链接已失效",
    missingBody: "这条核实记录找不到了。",
    missingAction: "去 SignalHire 验证候选人",
    searchBadge: "AI 人才报告",
    verifyBadge: "证据审计报告",
    searchContext: "岗位画像",
    verifyContext: "候选人证据审计",
    contextNote: "SignalHire 基于公开来源生成 · 候选人按 AI 方向分层 · 关键结论附可点击证据",
    noCandidates: "这份报告没有可展示的候选人结果。",
    searchCtaTitle: "想为你的 AI 岗位生成这样的候选名单？",
    searchCtaBody: "SignalHire 从公开来源搜索全球 AI 人才，并把论文、开源、实践和工作经历证据整理成可交付报告。",
    searchCtaButton: "生成 AI 人才候选名单",
    verifyCtaTitle: "想审计你自己的候选人证据？",
    verifyCtaBody: "SignalHire 从公开来源交叉验证候选人声称，标出已验证、未验证和矛盾点。",
    verifyCtaButton: "开始审计候选人",
    unknownCandidate: "未知候选人",
    missingMetaTitle: "报告不存在 · SignalHire",
    searchMetaSuffix: "核实报告",
    searchMetaDesc: "SignalHire 生成的 AI 人才候选名单与公开证据报告。",
    verifyMetaDesc: "SignalHire 生成的候选人证据审计报告。",
    missingMetaDesc: "这条 SignalHire 研究记录不可用。",
  },
  en: {
    missingTitle: "Report not found or link expired",
    missingBody: "This research record could not be found.",
    missingAction: "Verify a candidate with SignalHire",
    searchBadge: "AI talent report",
    verifyBadge: "Evidence audit report",
    searchContext: "Role profile",
    verifyContext: "Candidate evidence audit",
    contextNote: "Generated from public sources by SignalHire · Candidates are grouped by AI direction · Key conclusions include clickable evidence",
    noCandidates: "This report does not contain displayable candidate results.",
    searchCtaTitle: "Want to generate this kind of shortlist for your AI role?",
    searchCtaBody: "SignalHire searches public sources for global AI talent and turns papers, open-source work, practical output, and work history into a delivery-ready report.",
    searchCtaButton: "Generate an AI talent shortlist",
    verifyCtaTitle: "Want to audit your own candidate evidence?",
    verifyCtaBody: "SignalHire cross-checks candidate claims against public sources and marks verified, unverified, and contradicted points.",
    verifyCtaButton: "Start a candidate audit",
    unknownCandidate: "Unknown candidate",
    missingMetaTitle: "Report not found · SignalHire",
    searchMetaSuffix: "Evidence report",
    searchMetaDesc: "An AI talent shortlist and public evidence report generated by SignalHire.",
    verifyMetaDesc: "A candidate evidence audit report generated by SignalHire.",
    missingMetaDesc: "This SignalHire research record is unavailable.",
  },
} as const;

function rc(locale: Locale, key: keyof typeof REPORT_COPY.zh) {
  return REPORT_COPY[locale][key];
}

function normalizeLegacyClaim(claim: unknown): Claim | null {
  if (!isRecord(claim)) return null;
  const verdict = cleanString(claim.verdict);
  return {
    claim: cleanString(claim.claim),
    verdict: verdict === "verified" || verdict === "contradicted" ? verdict : "unverified",
    evidence: Array.isArray(claim.evidence)
      ? claim.evidence.filter(isRecord).map((evidence) => ({
          note: cleanString(evidence.note),
          url: cleanString(evidence.url),
        }))
      : [],
  };
}

function normalizeLegacyCandidates(result: unknown, locale: Locale): Candidate[] {
  if (!isRecord(result) || !Array.isArray(result.candidates)) return [];
  return result.candidates.filter(isRecord).map((candidate) => {
    const links = isRecord(candidate.links) ? candidate.links : {};
    return {
      name: cleanString(candidate.name) || rc(locale, "unknownCandidate"),
      headline: cleanString(candidate.headline),
      links: {
        github: cleanString(links.github) || null,
        linkedin: cleanString(links.linkedin) || null,
        other: cleanString(links.other) || null,
      },
      claims: Array.isArray(candidate.claims)
        ? candidate.claims.map(normalizeLegacyClaim).filter((claim): claim is Claim => Boolean(claim))
        : [],
      summary: cleanString(candidate.summary),
    };
  });
}

export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ lang?: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const { lang } = await searchParams;
  const locale = normalizeLocale(lang);
  const row = await getRunByIdWithTimeout(id);
  if (!row) return { title: rc(locale, "missingMetaTitle"), description: rc(locale, "missingMetaDesc") };
  return {
    title: `${row.label} - ${rc(locale, "searchMetaSuffix")} · SignalHire`,
    description: row.summary || (
      row.kind === "search"
        ? rc(locale, "searchMetaDesc")
        : rc(locale, "verifyMetaDesc")
    ),
  };
}

export default async function ReportPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ lang?: string }>;
}) {
  const { id } = await params;
  const { lang } = await searchParams;
  const locale = normalizeLocale(lang);
  const row = await getRunByIdWithTimeout(id);
  const talentResult: TalentSearchResult | null = row?.kind === "search" && isTalentSearchResult(row.result)
    ? normalizeTalentSearchResult(row.result)
    : null;
  const legacyCandidates = row?.kind === "search" && !talentResult
    ? normalizeLegacyCandidates(row.result, locale)
    : [];
  const cta = row?.kind === "verify"
    ? {
        title: rc(locale, "verifyCtaTitle"),
        body: rc(locale, "verifyCtaBody"),
        button: rc(locale, "verifyCtaButton"),
      }
    : {
        title: rc(locale, "searchCtaTitle"),
        body: rc(locale, "searchCtaBody"),
        button: rc(locale, "searchCtaButton"),
      };

  return (
    <div className="min-h-full" lang={locale === "en" ? "en" : "zh-CN"}>
      {/* 顶栏 */}
      <header className="mx-auto flex max-w-3xl items-center justify-between px-4 py-5">
        <Link href="/" className="flex items-center gap-2 font-semibold text-gray-900">
          <LogoMark className="h-8 w-8" />
          <span className="text-[17px] tracking-tight">SignalHire</span>
        </Link>
        <div className="flex items-center gap-2">
          <nav aria-label="Report language" className="inline-flex rounded-full bg-gray-100 p-1 text-xs font-semibold text-gray-500">
            {(["zh", "en"] as const).map((option) => (
              <Link
                key={option}
                href={`/r/${id}?lang=${option}`}
                className={`rounded-full px-2.5 py-1 transition ${locale === option ? "bg-white text-gray-950 shadow-sm" : "hover:text-gray-900"}`}
                aria-current={locale === option ? "true" : undefined}
              >
                {option === "zh" ? "中文" : "EN"}
              </Link>
            ))}
          </nav>
          <span className="hidden rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-600 sm:inline-flex">
            {row?.kind === "verify" ? rc(locale, "verifyBadge") : rc(locale, "searchBadge")}
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 pb-20">
        {!row ? (
          <div className="mt-10 rounded-[28px] border border-black/10 bg-white/86 p-8 text-center shadow-[0_18px_52px_rgba(15,23,42,0.06)] backdrop-blur-xl">
            <p className="text-lg font-semibold text-gray-900">{rc(locale, "missingTitle")}</p>
            <p className="mt-1 text-sm text-gray-500">{rc(locale, "missingBody")}</p>
            <Link href="/" className="mt-5 inline-flex items-center justify-center gap-2 rounded-full bg-gray-950 px-5 py-2.5 text-sm font-semibold text-white shadow-[0_16px_32px_rgba(15,23,42,0.18)] transition hover:-translate-y-0.5 hover:bg-gray-800">
              {rc(locale, "missingAction")}
              <FiArrowRight aria-hidden="true" />
            </Link>
          </div>
        ) : (
          <>
            {/* 上下文 */}
            <div className="mt-2">
              <p className="text-xs font-medium uppercase tracking-wide text-gray-400">
                {row.kind === "search" ? rc(locale, "searchContext") : rc(locale, "verifyContext")}
              </p>
              <blockquote className="mt-2 whitespace-pre-line rounded-xl border border-gray-200 bg-gray-50 p-4 text-sm text-gray-700">
                {row.query_text}
              </blockquote>
              <p className="mt-2 text-xs text-gray-400">
                {rc(locale, "contextNote")}
              </p>
            </div>

            {/* 结果 */}
            <div className="mt-6 space-y-4">
              {row.kind === "search" ? (
                talentResult ? (
                  <>
                    <SearchPlanView result={talentResult} locale={locale} />
                    <ShortlistDeliveryReportView result={talentResult} locale={locale} />
                    <SourceExecutionView result={talentResult} locale={locale} />
                    <CoverageBackfillView result={talentResult} locale={locale} />
                    <EvidenceCoverageView result={talentResult} locale={locale} />
                    <TalentMapView result={talentResult} locale={locale} />
                    <CandidateComparisonView result={talentResult} locale={locale} />
                    {talentResult.candidates.map((candidate, index) => (
                      <div key={`${candidate.name}-${index}`} className="space-y-3">
                        <EvidenceGraphView result={talentResult} candidate={candidate} locale={locale} />
                        <CandidateProfileView candidate={candidate} result={talentResult} locale={locale} />
                      </div>
                    ))}
                  </>
                ) : legacyCandidates.length > 0 ? (
                  legacyCandidates.map((c, i) => <CandidateCard key={i} c={c} delay={i * 90} locale={locale} />)
                ) : (
                  <p className="rounded-xl border border-gray-100 bg-white p-4 text-sm text-gray-500">
                    {rc(locale, "noCandidates")}
                  </p>
                )
              ) : (
                <TrustReportView r={row.result as VerifyReport} locale={locale} />
              )}
            </div>

            {/* CTA */}
            <div className="mt-10 rounded-[28px] border border-black/10 bg-white/86 p-6 text-center shadow-[0_18px_52px_rgba(15,23,42,0.06)] backdrop-blur-xl">
              <p className="text-base font-semibold text-gray-900">{cta.title}</p>
              <p className="mt-1 text-sm text-gray-500">{cta.body}</p>
              <Link href="/" className="mt-4 inline-flex items-center justify-center gap-2 rounded-full bg-gray-950 px-6 py-3 text-sm font-semibold text-white shadow-[0_16px_32px_rgba(15,23,42,0.18)] transition hover:-translate-y-0.5 hover:bg-gray-800">
                {cta.button}
                <FiArrowRight aria-hidden="true" />
              </Link>
            </div>
          </>
        )}

        <footer className="mt-10 text-center text-xs text-gray-400">
          Powered by SignalHire Deep Research
        </footer>
      </main>
    </div>
  );
}
